# Generated by Django 2.0.6 on 2018-07-07 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('description', models.CharField(max_length=1000)),
                ('contact', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=1000)),
            ],
        ),
    ]
