# Generated by Django 2.0.6 on 2018-07-08 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0002_sale'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recycle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=250)),
                ('name', models.CharField(max_length=250)),
                ('image', models.CharField(max_length=2500)),
                ('description', models.CharField(max_length=1000)),
                ('contact', models.DecimalField(decimal_places=0, max_digits=10)),
                ('address', models.CharField(max_length=1000)),
                ('city_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='Sale',
        ),
    ]
