# Generated by Django 2.0.7 on 2018-07-11 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0004_auto_20180712_0135'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recycle',
            old_name='address',
            new_name='Address',
        ),
        migrations.RenameField(
            model_name='recycle',
            old_name='contact',
            new_name='Contact',
        ),
        migrations.RenameField(
            model_name='recycle',
            old_name='description',
            new_name='Description',
        ),
        migrations.RenameField(
            model_name='recycle',
            old_name='image',
            new_name='Image',
        ),
        migrations.RenameField(
            model_name='recycle',
            old_name='name',
            new_name='Name',
        ),
        migrations.RemoveField(
            model_name='recycle',
            name='city_name',
        ),
        migrations.RemoveField(
            model_name='recycle',
            name='type',
        ),
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=0, default=1, max_digits=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recycle',
            name='Expected_price',
            field=models.DecimalField(decimal_places=0, default=5, max_digits=4),
            preserve_default=False,
        ),
    ]
