# Generated by Django 2.0.7 on 2018-07-11 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0005_auto_20180712_0334'),
    ]

    operations = [
        migrations.AddField(
            model_name='recycle',
            name='City',
            field=models.CharField(choices=[('GG', 'Gurugram'), ('DL', 'Delhi'), ('N', 'Noida'), ('GZB', 'Ghaziabad')], default='GZB', max_length=20),
        ),
        migrations.AddField(
            model_name='recycle',
            name='Type',
            field=models.CharField(choices=[('MA', 'Mobile Accessories'), ('HD', 'Hard Disk'), ('MP', 'Mobile Phone'), ('PP', 'PC Parts'), ('O', 'Others')], default='MA', max_length=20),
        ),
    ]
